### ISSUE TITLE
open_email does not appear to work

### ISSUE THREAD

**Issue by adamwong246** [DavyJonesLocker/capybara-email#38] opened 2014-02-21 01:59 UTC
```
    background do
      recipient_user = double()
      recipient_user.stub(:name) {'Ash Williams'}
      recipient_user.stub(:email) {'theKing@email.com'}

      message = mock_model( Message, 
        recipient: recipient_user
      )

      Mailer.sponsored_challenge_promotion(message).deliver!
      open_email('theKing@email.com')

    end

    scenario 'should say hello to the user' do
      current_email.should have_content "Hello, Ash"
    end
```

in this scenario, both `open_email` and `current_email` return nil

**Comment by lmcilwain** [comment] 2015-02-13 13:10
I simply get undefined method `open_email' even though I have the required specify in my rails_helper.rb.

**Comment by bcardarella** [comment] 2015-02-13 13:12
which version of rails and rspec?

**Comment by lmcilwain** [comment] 2015-02-13 13:14
Sorry I didn't mention that.

rails 4.1.2
rspec-rails 3.1.0
capybara-email 2.4.0

**Comment by chriswarren** [comment] 2015-03-11 21:56
Did anyone figure this out? I'm using Rails 4.2.0, rspec-rails 3.1.0, capybara-email 2.4.0 as well. I just started using this today, so haven't done much investigation yet, but if there's a solution out there that'd be great.

**Comment by chriswarren** [comment] 2015-03-12 14:48
Looks like it's related to `deliver_later`, at least for me. If I switch my code to use `deliver_now` the test passes. I have `config.active_job.queue_adapter` and `config.action_mailer.delivery_method` both set to `:test`, so I don't think the issue is there. Will continue to investigate.

**Comment by chriswarren** [comment] 2015-03-12 17:07
I was able to access the email by passing the action that sends the email to `perform_enqueued_jobs`. My test looks like
```
scenario "User requests password reset" do
  visit "/forgot_password"
  fill_in "Email", with: email

  perform_enqueued_jobs do
    click_button "Reset Password"
  end

  open_email(email)
  current_email.click_link "reset your password here"

  fill_in "Password", with: new_password
  click_button "Set Password"

  expect(current_path).to eq "/user"
end
```

Hope this helps.

**Comment by magegu** [comment] 2015-04-21 14:33
same here, current_mail is just nil 


Using rails 4.2.0
Using rspec-rails 3.2.1
Using capybara 2.4.4
Using capybara-email 2.4.0

**Comment by MatzFan** [comment] 2015-05-13 13:40
Had the same issue here in a Padrino app - so non-Rails, but uses the same ubiquitous Mail gem. Was solved by setting the delivery method in my spec_helper as described [here](https://github.com/mikel/mail#using-mail-with-testing-or-specing-libraries).
```
Mail.defaults do
  delivery_method :test
end
```
padrino 12.4
rspec 3.1.0
capybara 2.4.4
capybara-email 2.4.0

**Comment by brntsllvn** [comment] 2015-11-12 19:29
One possible gotcha...do not make the mistake, as I did, of including

ActionMailer::Base.delivery_method = :smtp

in config/environment.rb, which I incorrectly believed would be overridden by the more-specific config/environments/test.rb. Deleting the above line from config/environment.rb fixed the problem for me (i.e. open_email works)

**Comment by kaushikkanishka** [comment] 2016-06-23 02:13
I am little bit confused with this capybara email section that without giving the password   how we can open the email and read all the mails. Please help in email configuration in my project

**Comment by zavan** [comment] 2016-06-23 03:41
@kaushikkanishka When in test env, instead of sending email, Rails simply push emails into an array (`ActionMailer::Base.deliveries`). Capybara looks for the email in this array. 

See http://guides.rubyonrails.org/testing.html#functional-testing.

**Comment by hoenth** [comment] 2016-06-24 17:44
From @ghost's comment back in 2015, you may get an "undefined" error if you are trying to use the library in an email spec test. The DSL is not included by default in these tests. To include them, add 
````
include Capybara::Email::DSL
````
to the top of the email spec.

**Comment by amclelland** [comment] 2016-10-18 17:11
If anyone else is using the mail_safe gem, be sure to NOT include it in the testing group in your Gemfile. This will replace the 'to' email address with your initializer's settings.

**Comment by HarlemSquirrel** [comment] 2017-01-30 16:07
On rails 5 I was able to get this working by adding `sleep 1` in between the form submit that triggers my email send and `open_email`

**Comment by iamraffe** [comment] 2017-06-08 19:15
@HarlemSquirrel Are you on Rails 5.1? I'm getting nil on current_email after opening the email.

```
    visit root_url(subdomain: false)
    fill_in "claim your name", with: subdomain
    fill_in "email", with: 'email@example.com'
    click_button "Sign Up"
    set_host "#{subdomain}.lvh.me:5000"
    sleep 1
    open_email "email@example.com"
    current_email.click_link "Race ya' there"
```

**Comment by HarlemSquirrel** [comment] 2017-06-09 17:19
@iamraffe No, I haven't updated to 5.1 yet

**Comment by joethrive** [comment] 2018-10-22 17:39
Upgrading to Rails 5.2 and am getting nil current_email, same as @iamraffe 

Anyone have a solution to this?

**Comment by handofthecode** [comment] 2018-11-06 22:33
@joethrive
Make sure you follow the setup guide for capybara-email:
https://github.com/DavyJonesLocker/capybara-email#setting-your-test-host

Also, you might need to set your job queue adapter to inline for testing. 
config/environments/test.rb: config.active_job.queue_adapter = :inline

**Comment by frasermince** [comment] 2019-02-06 17:28
Any updates on this? I'm getting this on Rails 5.1 even after following the configuration to setup my test host.

**Comment by obfuscoder** [comment] 2021-08-02 13:18
I have a Rails 5.2 project with delayed_jobs gem where I just call ```Delayed::Worker.new.work_off```before ```open_email email```.  Setting the queue adapter to inline is another option and the recommended one as mentioned by @handofthecode. open_email will only be able open a **delivered** mail. I'll close this issue.

**Closed by obfuscoder** 2021-08-02 13:18 UTC
